### ISSUE TITLE
TypeError: Cannot call method 'Symbol'

### ISSUE THREAD

**Issue by arboleya** [rferro/plnx#3]
Hi, first of all, nice project! :)

I'm getting an error after calling the `returnTradeHistory` method a second time.

Code to reproduce the error:

``` javascript
var POLONIEX_KEY='....' ;
var POLONIEX_SECRET='...' ;

var polo = require('plnx');

var options = {
  key: POLONIEX_KEY,
  secret: POLONIEX_SECRET,
  currencyPair: 'all'
};

function fetch_trade_history(){
  polo.returnTradeHistory(options, function(err, data){
    console.log(data);
    setTimeout(fetch_trade_history, 1000);
  });
}

fetch_trade_history();
```

First time runs ok, but second time throws this:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.exports.(anonymous function) [as returnTradeHistory] (/plnx-error-reproduction/node_modules/plnx/lib/index.js:70:38)
    at fetch_trade_history [as _onTimeout] (/plnx-error-reproduction/test.js:14:8)
    at Timer.listOnTimeout (timers.js:92:15)
```

Apparently [this](https://github.com/rferro/plnx/blob/master/src/index.js#L44-L46) turn to [this](https://github.com/rferro/plnx/blob/master/lib/index.js#L69-L88), and at [this line](https://github.com/rferro/plnx/blob/master/lib/index.js#L70) we find the `Symbol.iterator()` thing which appears to be never defined anywhere.

What may be wrong with it? Can this be a babel thing? I'm not too much into Babel.

Thanks again for the project. :beers:

**Comment by arboleya** [comment]
Perhaps  this helps:
http://stackoverflow.com/a/29382912/999459
https://babeljs.io/docs/usage/polyfill/

**Comment by rferro** [comment]
@arboleya tks for your help! I test this and the problem is the reference of cfg.params. In this [line](https://github.com/rferro/plnx/blob/66b1f34aec39bd32d81d586a2d3e669578a77da7/lib/index.js#L63), the cfg.params changed and change the main static config object. In commit  4f1478d has fixed.

Tks!!

**Comment by arboleya** [comment]
Yep, I've opened a pull request with this exact fix. :v:
